In [144]:
import numpy as np
import scipy.integrate as spi
import scipy.linalg as la

from numpy.linalg import matrix_power as mpow

# 1. 
$$\int_0^\infty \frac{dx}{ax^2+b} = \frac{\pi}{2\sqrt{ab}}$$

In [12]:
def prob1(a,b,upper):
    def f(x):
        return 1/(a*x**2+b)
    I,abserr = spi.quad(f,0,upper)
    return I

In [16]:
prob1(10,10,1000)

0.15697963271282295

In [15]:
np.pi/(2*(10*10)**0.5)

0.15707963267948966

# 2.
$$\int_0^1 \frac{dx}{x^a(1-x)^{1-a}} = \frac{\pi}{\sin(\pi a)}, \ \ 0<a<1 $$

In [22]:
def prob2(a):
    def f(x):
        return 1/(x**a*(1-x)**(1-a))
    I,abserr = spi.quad(f,0,1)
    if (a > 0 and a < 1):
        return I 
    else: 
        print('Error, a must be between 0 and 1 ')
        return None 

In [23]:
prob2(2)

Error, a must be between 0 and 1 


/opt/conda/lib/python3.5/site-packages/scipy/integrate/quadpack.py:356: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)


In [24]:
prob2(0.2)

5.344796661587762

In [25]:
np.pi/(np.sin(np.pi*0.2))

5.3447966605779751

# 3. 
$$\int_0^1 \frac{\ln(x)}{x+1} dx  = \frac{-\pi^2}{12} $$

In [28]:
def prob3(x):
    def f(x):
        return np.log(x)/(x+1)
    I,abserr = spi.quad(f,0,1)
    return I 


In [29]:
prob3(100)

-0.8224670334241143

In [30]:
-np.pi**2/12

-0.8224670334241132

# 4.  
$$\int_0^\infty \ln \frac{a^2+x^2}{b^2+x^2} dx = \pi(a-b), \ \ a,b > 0 $$ 

In [31]:
def prob4(a,b,upper):
    def f(x):
        return np.log((a**2+x**2)/(b**2+x**2))
    I, abserr = spi.quad(f,0,upper)
    if (a > 0 and b > 0):
        return I 
    else: 
        print('Error, a and b must be greater than 0')
        return None 

In [32]:
prob4(1,2,1000)

-3.1385926560897945

In [34]:
np.pi*(1-2)

-3.141592653589793

In [36]:
prob4(0,1,10)

Error, a and b must be greater than 0


# 5. 
$$\int_0^\infty \frac{\cos(ax)}{\sqrt{x}} dx = \sqrt{\frac{\pi}{2a}}, \ \ a > 0 $$ 

In [37]:
def prob5(a,upper):
    def f(x):
        return np.cos(a*x)/(x)**0.5
    I,abserr = spi.quad(f,0,upper)
    if a > 0: 
        return I 
    else: 
        print('Error, a must be greater than 0 ')

In [41]:
prob5(10,5)

0.3841715748890306

In [39]:
(np.pi/(2*10))**0.5

0.3963327297606011

In [44]:
prob5(0,10)

Error, a must be greater than 0 


# 6. 
$$\int_0^\infty e^{-ax}\sin(bx)dx = \frac{b}{a^2+b^2}, \ \ a > 0 $$

In [55]:
def prob6(a,b,upper):
    def f(x):
        return np.exp(-a*x)*np.sin(b*x)
    if a > 0: 
        I,abserr = spi.quad(f,0,upper)
        return I 
    else: 
        print('Error, a must be greater than 0 ')
        

In [56]:
prob6(0,10,10)

Error, a must be greater than 0 


In [57]:
prob6(10,10,100)

0.049999999999999996

In [59]:
10/(10**2+10**2)

0.05

Let's try problem 6 with `trapz`. 

In [64]:
def prob6trapz(a,b,upper=100):
    x = np.linspace(0,upper)
    y = np.exp(-a*x)*np.sin(b*x)
    return spi.trapz(y,x)

In [65]:
prob6trapz(10,10)

2.7965266697282653e-09

# 7. 
Use `trapz`,`simps`, and `quad` to compute the following: 
$$\int \cos(x)^3 dx = \sin(x) - \frac{1}{3}\sin^3(x)$$

In [72]:
x = np.linspace(0,100,1000)
y = np.cos(x)**3 
print(spi.trapz(y,x))
print(spi.simps(y,x))


-0.46214301006
-0.463225912943


In [68]:
def f7(x):
    return np.cos(x)**3 
I,abserr = spi.quad(f7,0,100)
I

-0.4630872174907519

** Expected Result ** 

In [71]:
result7 = np.sin(x) - 1/3 * np.sin(x)**3
result7[-1]

-0.46308721749074822

# 8. 
Use `trapz`,`simps`, and `quad` to compute the following: 
$$\int \sin(a+bx)dx = \frac{-1}{b}\cos(a+bx)$$

In [96]:
def prob8(a,b):
    x = np.linspace(0,100,100000)
    y = np.sin(a+b*x)
    print(spi.trapz(y,x))
    print(spi.simps(y,x))

In [97]:
prob8(10,10)

-0.081702837505
-0.0817035119374


In [85]:
def prob8quad(a,b):
    def f8(x):
        return np.sin(a+b*x)
    I,abserr = spi.quad(f8,0,10000)
    return I 

In [95]:
prob8quad(10,10)

/opt/conda/lib/python3.5/site-packages/scipy/integrate/quadpack.py:356: IntegrationWarning: The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze 
  the integrand in order to determine the difficulties.  If the position of a 
  local difficulty can be determined (singularity, discontinuity) one will 
  probably gain from splitting up the interval and calling the integrator 
  on the subranges.  Perhaps a special-purpose integrator should be used.
  warnings.warn(msg, IntegrationWarning)


-0.08155443064986515

** Expected Result ** 

In [98]:
x = np.linspace(0,100,1000)
res8 = -1/10 * np.cos(10+10*x)
res8[-1]

0.0022036345251931341

# 9. 
$$\int_0^\infty \frac{dx}{1+e^{ax}} = \frac{\ln2}{a}$$

In [99]:
def prob9(a,upper):
    def f(x):
        return 1/(1+np.exp(a*x))
    I,abserr = spi.quad(f,0,upper)
    return I 

In [101]:
prob9(1,100)

0.6931471805599453

In [103]:
np.log(2)

0.69314718055994529

In [107]:
prob9(0.01,10)

4.875052048637442

# 10. 
$$\int_0^\infty e^{-\mu x}\ln(x) dx = -\frac{1}{\mu}(C+\ln(\mu)), \ \mu > 0, \ C = 0.5772... $$ 

In [109]:
def prob10(mu,upper):
    def f(x):
        return np.exp(-mu*x)
    if mu > 0: 
        I,abserr = spi.quad(f,0,upper)
        return I 
    else: 
        print('Error mu must be greater than 0 ')

In [117]:
prob10(5,1000)

0.19999999999999996

In [115]:
-1/5* (0.57722 + np.log(5))

-0.43733158248682003

# 11. 
$$\int_0^\infty \frac{\sin(x)\cos(ax)}{x}dx = \frac{\pi}{2} \ \ \text{if} \  |a| < 1, \ \ \frac{\pi}{4} \ \text{if} \ |a| = 1, \ \text{or} \  0 \ \ \text{if} \  1 < |a|$$

In [126]:
def prob11(a,upper=10):
    def f(x):
        return (np.sin(x)*np.cos(a*x))/x
    I,abserr = spi.quad(f,0,upper)
    return I 

In [127]:
# Case where a = 1
prob11(1)

0.7741208505217201

In [123]:
np.pi/4

0.7853981633974483

In [128]:
# Case where a < 1 
prob11(0.5)

1.5840628443265214

In [129]:
np.pi/2

1.5707963267948966

In [131]:
# Case where a > 1 
prob11(2)

-0.045795527094261344

### The following matrix problems are from `Linear Algebra and Its Applications (Lay) 3rd Ed. `

# 12. 

$A=PDP^{-1}$. Let matrix be P = $\begin{bmatrix} 5 & 7 \\ 2 & 3 \end{bmatrix}$, $D = \begin{bmatrix} 2 & 0 \\ 0 & 1 \end{bmatrix}$. Solve $A^4$. 

In [3]:
P = np.array([[5,7],[2,3]])
D = np.array([[2,0],[0,1]])
Pinv = la.inv(P)

In [5]:
A = P@D@Pinv

In [7]:
mpow(A,4)

array([[ 226., -525.],
       [  90., -209.]])

# 13. 
$A=PDP^{-1}$. Let matrix be P = $\begin{bmatrix} 1 & 2 \\ 2 & 3 \end{bmatrix}$, $D = \begin{bmatrix} 1 & 0 \\ 0 & 3 \end{bmatrix}$. Solve $A^4$. 

In [8]:
P = np.array([[1,2],[2,3]])
D = np.array([[1,0],[0,3]])
Pinv = la.inv(P)
A = P@D@Pinv

In [9]:
mpow(A,4)

array([[ 321., -160.],
       [ 480., -239.]])

# 14. 
A = np.array([[2,-1,-1],[1,4,1],[-1,-1,2]])

Find the diagonalized matrix $D$

In [10]:
A = np.array([[2,-1,-1],[1,4,1],[-1,-1,2]])

In [11]:
evals,evecs = la.eig(A)

In [18]:
evals

array([ 2.+0.j,  3.+0.j,  3.+0.j])

In [21]:
D = np.diag(evals)
D

array([[ 2.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  3.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  3.+0.j]])

# 15. 
Diagonalize $\begin{bmatrix} 1 & 0 \\ 6 & -1 \end{bmatrix}$

In [39]:
A = np.array([[1,0],[6,-1]])

In [37]:
evals,evecs = la.eig(A)

In [40]:
evals
np.diag(evals)

array([[-1.+0.j,  0.+0.j],
       [ 0.+0.j,  1.+0.j]])

# 16. 
Diagonalize $\begin{bmatrix} 5 & -3 & 0 & 9 \\ 0& 3 & 1 & -2 \\ 0 & 0 & 2 & 0 \\ 0 & 0 & 0 & 2 \end{bmatrix}$

In [41]:
A = np.array([[5,-3,0,9],[0,3,1,-2],[0,0,2,0],[0,0,0,2]])
A

array([[ 5, -3,  0,  9],
       [ 0,  3,  1, -2],
       [ 0,  0,  2,  0],
       [ 0,  0,  0,  2]])

In [43]:
evals,evecs = la.eig(A)
evals

array([ 5.+0.j,  3.+0.j,  2.+0.j,  2.+0.j])

In [44]:
evecs

array([[ 1.        ,  0.83205029, -0.57735027, -0.40824829],
       [ 0.        ,  0.5547002 , -0.57735027,  0.81649658],
       [ 0.        ,  0.        ,  0.57735027,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.40824829]])

In [46]:
D = np.diag(evals)
D

array([[ 5.+0.j,  0.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  3.+0.j,  0.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  2.+0.j,  0.+0.j],
       [ 0.+0.j,  0.+0.j,  0.+0.j,  2.+0.j]])

# 17. 
Diagonalize $\begin{bmatrix} 9 & -4 & -2 & -4 \\ -56& 32 & -28 & 44 \\ -14 & -14 & 6 & -14 \\ 42 & -33 & 21 & -45 \end{bmatrix}$

In [49]:
A = np.array([[9,-4,-2,-4],[-56,32,-28,44],[-14,-14,6,-14],[42,-33,21,-45]])
A

array([[  9,  -4,  -2,  -4],
       [-56,  32, -28,  44],
       [-14, -14,   6, -14],
       [ 42, -33,  21, -45]])

In [51]:
evals,evecs = la.eig(A)

In [52]:
evals

array([-12.+0.j, -12.+0.j,  13.+0.j,  13.+0.j])

In [54]:
D = np.diag(evals)
D

array([[-12.+0.j,   0.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j, -12.+0.j,   0.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,  13.+0.j,   0.+0.j],
       [  0.+0.j,   0.+0.j,   0.+0.j,  13.+0.j]])

# 18. 

Which sets of vectors are orthogonal? 

In [68]:
v1 = np.array([[-1],[4],[-3]])
v2 = np.array([[5],[2],[1]])
v3 = np.array([[3],[-4],[-7]])

In [67]:
np.dot([-1,4,-3],[5,2,1]) # To use np.dot we can't have the arrays set up as we do above 

0

This means v1 and v2 are orthogonal. 

In [69]:
np.dot([-1,4,-3],[3,-4,-7])

2

v1 and v3 are not orthogonal.

In [70]:
np.dot([5,2,1],[3,-4,-7])

0

v2 and v3 are orthogonal. 

# 19. 
Verify $u_1, u_2$ are orthogonal. Then find the orthogonal $proj_uy$ onto Span$\{u_1,u_2\}$. 

In [74]:
def proj(v,w):
    '''Project vector v onto w.'''
    v = np.array(v)
    w = np.array(w)
    return np.sum(v * w)/np.sum(w * w) * w   # or (v @ w)/(w @ w) * w

In [108]:
def length(u):
    """ Calculates the length of a vector """
    return np.linalg.norm(u)

In [106]:
u1 = [-7,1,4]
u2 = [-1,1,-2]
y = [-9,1,6]

In [107]:
np.dot(u1,u2)

0

In [112]:
proj(y,u1) + proj(y,u2)

array([-9.,  1.,  6.])

# 20. 
Verify $u_1, u_2$ are orthogonal. Then find the orthogonal $proj_uy$ onto Span$\{u_1,u_2\}$. 

In [113]:
y = [-1,4,3]
u1 = [1,1,0]
u2 = [-1,1,0]

In [114]:
np.dot(u1,u2)

0

In [115]:
proj(y,u1) + proj(y,u2)

array([-1.,  4.,  0.])

# 21. 
Verify $u_1, u_2$ are orthogonal. Then find the orthogonal $proj_uy$ onto Span$\{u_1,u_2\}$. 

In [116]:
y = [-1,2,6]
u1 = [3,-1,2]
u2 = [1,-1,-2]

In [117]:
np.dot(u1,u2)

0

In [118]:
proj(y,u1)+proj(y,u2)

array([-1.,  2.,  6.])

# 22. 
Find the closest point to $y$ in the subspace $W$ spanned by $v_1, v_2$. 

In [119]:
y = [3,1,5,1]
v1 = [3,1,-1,1]
v2 = [1,-1,1,-1]

In [120]:
proj(y,v1)+proj(y,v2)

array([ 3., -1.,  1., -1.])

# 23. 
Find the closest point to $y$ in the subspace $W$ spanned by $v_1, v_2$. 

In [121]:
y = [3,-1,1,13]
v1 = [1,-2,-3,1]
v2 = [-4,1,0,3]

In [122]:
proj(y,v1) + proj(y,v2)

array([-3., -1., -3.,  4.])

# 24. 

Find eigenvectors and determinant of A 

In [123]:
A = np.array([[12,1,4],[2,11,4],[1,3,7]])
A

array([[12,  1,  4],
       [ 2, 11,  4],
       [ 1,  3,  7]])

In [124]:
evals, evecs = la.eig(A)

In [125]:
evals

array([ 10.+0.j,  15.+0.j,   5.+0.j])

In [127]:
la.det(A)

750.0

# 25. 
Find determinant of A 

In [128]:
A = np.array([[1,5,-6],[-1,-4,4],[-2,-7,9]])
A

array([[ 1,  5, -6],
       [-1, -4,  4],
       [-2, -7,  9]])

In [129]:
la.det(A)

2.9999999999999996

# 26. 
Find the determinant of A 

In [130]:
A = np.array([[2,5,4,1],[4,7,6,2],[6,-2,-4,0],[-6,7,7,0]])
A

array([[ 2,  5,  4,  1],
       [ 4,  7,  6,  2],
       [ 6, -2, -4,  0],
       [-6,  7,  7,  0]])

In [131]:
la.det(A)

6.000000000000036

# 27. 
Compute $AB$ between matrices $A$ and $B$. 

In [133]:
A = np.array([[2,3],[1,-5]])
B = np.array([[4,3,6],[1,-2,3]])
A @ B 

array([[11,  0, 21],
       [-1, 13, -9]])

# 28. 
Compute $AB$ between matrices $A$ and $B$. Show that $AB \neq BA$ 

In [134]:
A = np.array([[5,1],[3,-2]])
B = np.array([[2,0],[4,3]])

In [135]:
A @ B 

array([[14,  3],
       [-2, -6]])

In [136]:
B @ A 

array([[10,  2],
       [29, -2]])

We can see that AB is different from BA. 

# 29. 
Solve the linear system 

In [141]:
A = np.array([[1,3,-4],[1,5,2],[-3,-7,6]])
b = np.array([[-2],[4],[12]])
x = la.solve(A,b)

In [142]:
x

array([[ -1.10000000e+01],
       [  3.00000000e+00],
       [  1.48029737e-16]])

In [143]:
A @ x 

array([[ -2.],
       [  4.],
       [ 12.]])

# 30. 
Solve the linear system

In [153]:
A = np.array([[5,-2,10],[-2,4,5],[3,-6,-6]])
b = np.array([[10],[3],[2]])
x = la.solve(A,b)

In [154]:
x

array([[-10.66666667],
       [-10.        ],
       [  4.33333333]])

In [155]:
A @ x 

array([[ 10.],
       [  3.],
       [  2.]])

# 31 

$$\int \frac{x dx}{(a+bx)^3}  = \frac{1}{b^2}\left(-\frac{1}{a+bx} + \frac{a}{2(a+bx)^2}\right)$$

In [163]:
def prob31(a,b,upper):
    def f(x):
        return x/(a+b*x)**3
    I,abserr = spi.quad(f,0,upper)
    return I 

In [164]:
prob31(5,9,100)

0.0012209639510393443

In [162]:
a = 5
b = 9
x = np.linspace(0,100,1000)
res31 = 1/(b**2) * (- 1/(a+b*x) + a/(2*(a+b*x)**2))
res31[-1]

-1.3603950195222338e-05

# 32. 

$$\int \frac{dx}{a^2+x^2} = \frac{1}{a} \arctan\frac{x}{a} $$ 

In [165]:
def prob31(a,upper):
    def f(x):
        return 1/(a**2+x**2)
    I,abserr = spi.quad(f,0,upper)
    return I 

In [176]:
prob31(9,100)

0.1645597947338836

In [178]:
def prob31trapz(a,upper):
    x = np.linspace(0,100,100)
    y = 1/(a**2+x**2)
    return spi.trapz(y,x)

In [179]:
prob31trapz(9,100)

0.16455962740824795

In [180]:
def prob31simps(a,upper):
    x = np.linspace(0,100,100)
    y = 1/(a**2+x**2)
    return spi.simps(y,x)

In [181]:
prob31simps(9,100)

0.16454687001037377

In [182]:
prob31(9,100) - prob31trapz(9,100)

1.6732563565269309e-07

In [183]:
prob31(9,100) - prob31simps(9,100)

1.2924723509832869e-05

# 33. 
$$\int \frac{x dx}{a^2 + x^2} = \frac{1}{2} \ln (a^2 + x^2) $$

In [184]:
def prob33(a,lower=0,upper=100):
    def f(x):
        return x/(a**2+x**2)
    I,abserr = spi.quad(f,lower,upper)
    return I 

In [185]:
prob33(19)

1.678463038959434

In [190]:
x = np.linspace(0,100,100)
res33 = 0.5 * np.log(19**2 + x**2)
res33[-1]

4.6229020181258758

# 34. 
$$\int_0^\infty \frac{x^{a-1} dx}{x+1} = \frac{\pi}{\sin(\pi a)}, \ 0 < a < 1 $$

In [201]:
def prob34(a):
    def f(x):
        return x**(a-1)/(x+1)
    I,abserr = spi.quad(f,0,np.inf)
    if (0 < a and a < 1):
        return I 
    else:
        print('Error, a must be in the range (0,1)')
        return None 

In [202]:
prob34(9)

Error, a must be in the range (0,1)


/opt/conda/lib/python3.5/site-packages/scipy/integrate/quadpack.py:356: IntegrationWarning: The algorithm does not converge.  Roundoff error is detected
  in the extrapolation table.  It is assumed that the requested tolerance
  cannot be achieved, and that the returned result (if full_output = 1) is 
  the best which can be obtained.
  warnings.warn(msg, IntegrationWarning)


In [203]:
prob34(0.5)

3.141592653591144

In [204]:
np.pi/np.sin(np.pi * 0.5)

3.1415926535897931

In [206]:
prob34(0.9)

10.166407384735095

In [207]:
np.pi/np.sin(np.pi*0.9)

10.166407384630517

# 35. 
$$ \int_0^\infty \frac{x^{\lambda - 1} dx}{(1+ax)^2} = \frac{\pi(1-\lambda)}{a^\lambda \sin(\pi \lambda)}, \ 0 < \lambda < 2 $$

In [208]:
def prob35(a,lambdaa):
    def f(x):
        return x**(lambdaa - 1)/(1+a*x)**2
    I, abserr = spi.quad(f,0,np.inf)
    if (lambdaa < 2 and lambdaa > 0):
        return I 
    else: 
        print('Error, lambda must be in the range (0,2)')
        return None 

In [209]:
prob35(9,1)

0.1111111111111111

In [211]:
np.pi*(1-1)/(9**1 * np.sin(np.pi * 1))

0.0

In [213]:
prob35(35,0.2)

2.099943285574904

In [214]:
np.pi*(1-0.2)/(35**0.2 * np.sin(np.pi * 0.2))

2.0999432849930888

# 36. 

$$\int_0^1 \frac{dx}{x^2 + 2x\cos(\beta) + 1} = \frac{\beta}{2\sin\beta} $$

In [215]:
def prob36(beta):
    def f(x):
        return 1/(x**2 + 2*x*np.cos(beta)+1)
    I,abserr = spi.quad(f,0,1)
    return I 

In [223]:
prob36(1)

0.5941975528890605

In [224]:
1/(2*np.sin(1))

0.59419755288906062

# 37. 
$$ \int_0^1 \frac{x^a dx}{(1-x)^a} = \frac{\pi a}{\sin(\pi a)}, \ \ -1 < a < 1 $$

In [230]:
def prob37(a):
    def f(x):
        return x**a / (1-x)**a 
    I, abserr = spi.quad(f,0,1)
    if (a > -1 and a < 1):
        return I 
    else: 
        print('Error, a must be in the range (-1,1)')
        return None 

In [235]:
prob37(0.5)

1.5707963267949785

In [236]:
np.pi*(0.5)/np.sin(np.pi*0.5)

1.5707963267948966

In [238]:
prob37(-2)

Error, a must be in the range (-1,1)


/opt/conda/lib/python3.5/site-packages/scipy/integrate/quadpack.py:356: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  warnings.warn(msg, IntegrationWarning)


# 38. 
$$\int_0^1 x^{p-1}(1-x^q)^{-p/q} dx = \frac{\pi}{q \sin(\pi \ p/q)}, \ \ q > p > 0 $$ 

In [242]:
def prob38(q,p):
    def f(x):
        return x**(p-1)*(1-x**q)**(-p/q)
    I, abserr = spi.quad(f,0,1)
    if (q > p and p > 0):
        return I 
    else: 
        print('Error, q must be larger than p and larger than 0')
        return None 

In [246]:
prob38(24,10)

0.13551733511717706

In [248]:
np.pi/(24 * np.sin(np.pi * 10/24))

0.13551733511720074

# 39. 
$$ \int_0^1 \frac{dx}{\sqrt{(1+a^2x)(1-x)}} = \frac{2}{a}\arctan a $$

In [253]:
def prob39(a):
    def f(x):
        return 1 / ((1+a**2*x)*(1-x))**0.5
    I, abserr = spi.quad(f,0,1)
    return I 

In [254]:
prob39(9)

0.32447535680479

In [252]:
2/9 * np.arctan(9)

0.32447535680466683

# 40 
$$ \int_0^\infty \frac{dx}{1+e^{ax}} = \frac{\ln2}{a} $$ 

In [263]:
def prob40(a):
    def f(x):
        return 1 / (1+np.exp(a*x))
    I, abserr = spi.quad(f,0,1)
    return I 

In [264]:
prob40(5)

0.13728636641416544

In [265]:
np.log(2)/5

0.13862943611198905